export type Order = {
  method: OrderMethods;
  params: OrderParams;
  req_id: number;
};

type OrderParams = {
  order_type: OrderType;
  side: OrderSide;
  order_qty: number;
  symbol: string;
  limit_price: number;
  limit_price_type: OrderPriceType;
  triggers: OrderTriggers[];
  conditional: OrderConditional;
};

type OrderMethods = ["add_order", "amend_order", "edit_order"];
type OrderSide = ["Buy", "Sell"];
type OrderType = [
  "limit",
  "market",
  "iceberg",
  "stop-loss",
  "stop-loss-limit",
  "take-profit",
  "take-profit-limit",
  "trailing-stop",
  "trailing-stop-limit",
  "settle-position",
];

type OrderTriggers = {
  reference: OrderTriggerReference;
  index: number;
  last: number;
  price_type: OrderPriceType;
};
type OrderTriggerReference = ["index", "last"];

type OrderConditional = {
  order_type: CondtionalOrderType;
  limit_price: number;
  limit_price_type: OrderPriceType;
  trigger_price: number;
  trigger_price_type: OrderPriceType;
};
type OrderPriceType = ["static", "pct", "quote"];
type CondtionalOrderType = [
  "limit, stop-loss, stop-loss-limit, take-profit, take-profit-limit, trailing-stop, trailing-stop-limit]",
];

//// TO ADD
/*
time_in_force
string
Possible values: [gtc, gtd, ioc]
Default value: gtc
Time-in-force specifies how long an order remains in effect before being expired.

gtc: Good Till Canceled - until user has cancelled.
gtd: Good Till Date - until expire_time parameter.
ioc: Immediate Or Cancel - immediately cancels back any quantity that cannot be filled on arrival.
margin
boolean
Possible values: [false, true]
Default value: false
Funds the order on margin using the maximum leverage for the pair (maximum is leverage of 5).
post_only
boolean
conditional
Condition: Orders with limit price only.
Possible values: [true, false]
Default value: false
Cancels the order if it will take liquidity on arrival. Post only orders will always be posted passively in the book.

reduce_only
boolean
Possible values: [true, false]
Default value: false
Reduces an existing margin position without opening an opposite long or short position worth more than the current value of your leveraged assets.

effective_time
string
Format: RFC3339
Example: 2022-12-25T09:30:59Z
Scheduled start time (precision to seconds).
expire_time
string
conditional
Condition: GTD orders only.
Format: RFC3339
Example: 2022-12-25T09:30:59Z
Expiration time of the order (precision to seconds). GTD orders can have an expiry time up to one month in future.
deadline
string
Format: RFC3339
Example: 2022-12-25T09:30:59.123Z
Range of valid offsets (from current time) is 500 milliseconds to 60 seconds, default is 5 seconds. The precision of this parameter is to the millisecond. The engine will prevent this order from matching after this time, it provides protection against latency on time sensitive orders.

cl_ord_id
string
Adds a alphanumeric client order identifier which uniquely identifies an open order for each client. This field is mutually exclusive with order_userref parameter.

The cl_ord_id parameter can be one of the following formats:

Long UUID: 6d1b345e-2821-40e2-ad83-4ecb18a06876 32 hex characters separated with 4 dashes.
Short UUID: da8e4ad59b78481c93e589746b0cf91f 32 hex characters with no dashes.
Free text: arb-20240509-00010 Free format ascii text up to 18 characters.
order_userref
integer
This is an optional non-unique, numeric identifier which can associated with a number of orders by the client. This field is mutually exclusive with cl_ord_id parameter.

Many clients choose a unique integer value generated by their systems (i.e. a timestamp). However, because we don't enforce uniqueness on our side, it can also be used to easily tag a group of orders for querying or cancelling.


*/
